import { Community, Persona } from "../types";

const now = Date.now();
const t = (minsAgo: number) => now - minsAgo * 60 * 1000;

export const COMMUNITIES: Community[] = [
  {
    id: "career-pressure",
    name: "Career Pressure",
    category: "Work & Career",
    description: "Navigating burnout, toxic workplaces, and career pivots",
    emoji: "💼",
    sizeType: "large",
    memberCount: 128,
    activeNow: 14,
    seedMessages: [
      { id: "cp1", communityId: "career-pressure", anonymousName: "QuietMaple", content: "Anyone else feel like they're invisible at work no matter how hard they try?", timestamp: t(45) },
      { id: "cp2", communityId: "career-pressure", anonymousName: "SilverFox22", content: "Yes. I've been passed over for promotion three times this year. It's exhausting.", timestamp: t(38) },
      { id: "cp3", communityId: "career-pressure", anonymousName: "TealStorm", content: "Have you talked to your manager directly? Sometimes they genuinely don't notice.", timestamp: t(30) },
      { id: "cp4", communityId: "career-pressure", anonymousName: "QuietMaple", content: "I tried once and it got awkward. I'm scared to rock the boat.", timestamp: t(22) },
      { id: "cp5", communityId: "career-pressure", anonymousName: "RiverReed", content: "That fear is so real. But staying silent cost me two years of my career. Advocate for yourself ❤️", timestamp: t(10) },
    ],
  },
  {
    id: "burnout",
    name: "Burnout Recovery",
    category: "Work & Career",
    description: "Support for those running on empty and learning to rest",
    emoji: "🔥",
    sizeType: "large",
    memberCount: 203,
    activeNow: 31,
    seedMessages: [
      { id: "br1", communityId: "burnout", anonymousName: "GrayPebble", content: "Day 4 of my mental health leave. I still feel guilty for taking it.", timestamp: t(60) },
      { id: "br2", communityId: "burnout", anonymousName: "MossyCreek", content: "The guilt is part of burnout. You're not lazy — your body forced a stop.", timestamp: t(52) },
      { id: "br3", communityId: "burnout", anonymousName: "GrayPebble", content: "How long did it take you to feel human again?", timestamp: t(40) },
      { id: "br4", communityId: "burnout", anonymousName: "MossyCreek", content: "Honestly? Three weeks before I stopped dreaming about work emails.", timestamp: t(28) },
      { id: "br5", communityId: "burnout", anonymousName: "WarmBirch", content: "Solidarity. It gets better. Be patient with yourself.", timestamp: t(5) },
    ],
  },
  {
    id: "breakup",
    name: "Breakup Recovery",
    category: "Relationships",
    description: "Healing after heartbreak — no judgment, just support",
    emoji: "💔",
    sizeType: "small",
    memberCount: 9,
    activeNow: 3,
    seedMessages: [
      { id: "bkp1", communityId: "breakup", anonymousName: "BlueDawn", content: "6 weeks post breakup and I still check their Instagram. Why can't I stop?", timestamp: t(90) },
      { id: "bkp2", communityId: "breakup", anonymousName: "SoftCoral", content: "Because your brain is grieving. It's looking for proof they miss you too.", timestamp: t(80) },
      { id: "bkp3", communityId: "breakup", anonymousName: "BlueDawn", content: "That makes sense and hurts at the same time.", timestamp: t(72) },
      { id: "bkp4", communityId: "breakup", anonymousName: "ClearLake", content: "Try the 30-day no-contact. Changed my life.", timestamp: t(55) },
      { id: "bkp5", communityId: "breakup", anonymousName: "SoftCoral", content: "^^ this. Also journal. Get it out of your head.", timestamp: t(20) },
    ],
  },
  {
    id: "midlife",
    name: "Mid-life Transition",
    category: "Life Stages",
    description: "Identity shifts, purpose questions, and reinvention after 40",
    emoji: "🌅",
    sizeType: "large",
    memberCount: 87,
    activeNow: 9,
    seedMessages: [
      { id: "ml1", communityId: "midlife", anonymousName: "OakRoot", content: "Turned 45 last week and suddenly nothing I've built feels like me anymore.", timestamp: t(120) },
      { id: "ml2", communityId: "midlife", anonymousName: "WildSage", content: "That's not a crisis — that's clarity. You're finally hearing yourself.", timestamp: t(100) },
      { id: "ml3", communityId: "midlife", anonymousName: "OakRoot", content: "I wish it felt that poetic. Mostly it just feels like panic.", timestamp: t(85) },
      { id: "ml4", communityId: "midlife", anonymousName: "CopperLight", content: "Panic is okay. Let it tell you what it's scared to lose.", timestamp: t(40) },
      { id: "ml5", communityId: "midlife", anonymousName: "WildSage", content: "Agreed. This is the most honest I've ever been with myself.", timestamp: t(15) },
    ],
  },
  {
    id: "academic-stress",
    name: "Academic Stress",
    category: "Education",
    description: "Exam anxiety, imposter syndrome, and student burnout",
    emoji: "📚",
    sizeType: "large",
    memberCount: 156,
    activeNow: 22,
    seedMessages: [
      { id: "as1", communityId: "academic-stress", anonymousName: "NightOwl99", content: "I have finals in 3 days and I can't make myself start studying. Procrastination spiral.", timestamp: t(35) },
      { id: "as2", communityId: "academic-stress", anonymousName: "CalmMist", content: "Pomodoro method. 25 min on, 5 min break. It tricks your brain.", timestamp: t(28) },
      { id: "as3", communityId: "academic-stress", anonymousName: "NightOwl99", content: "I tried that but I end up on my phone during breaks.", timestamp: t(20) },
      { id: "as4", communityId: "academic-stress", anonymousName: "IvyLeaf", content: "Phone in another room. Seriously. Or give it to a friend.", timestamp: t(12) },
      { id: "as5", communityId: "academic-stress", anonymousName: "CalmMist", content: "You can do this. Done is better than perfect for first drafts.", timestamp: t(3) },
    ],
  },
  {
    id: "general-wellness",
    name: "General Wellness",
    category: "Wellness",
    description: "A space for everyday mental health check-ins and wins",
    emoji: "🌿",
    sizeType: "large",
    memberCount: 312,
    activeNow: 47,
    seedMessages: [
      { id: "gw1", communityId: "general-wellness", anonymousName: "SunrisePath", content: "Small win today: I went outside for 10 minutes and it actually helped.", timestamp: t(25) },
      { id: "gw2", communityId: "general-wellness", anonymousName: "PetalBreeze", content: "That counts! Nature resets something in us.", timestamp: t(20) },
      { id: "gw3", communityId: "general-wellness", anonymousName: "QuietRiver", content: "What's everyone doing for sleep lately? Mine is wrecked.", timestamp: t(15) },
      { id: "gw4", communityId: "general-wellness", anonymousName: "SunrisePath", content: "No screens 1 hour before bed + chamomile tea. Game changer for me.", timestamp: t(8) },
      { id: "gw5", communityId: "general-wellness", anonymousName: "PetalBreeze", content: "Same + magnesium glycinate. Look it up.", timestamp: t(2) },
    ],
  },
  {
    id: "anxiety-circle",
    name: "Anxiety Circle",
    category: "Mental Health",
    description: "For those with racing thoughts and a restless mind",
    emoji: "🌀",
    sizeType: "small",
    memberCount: 7,
    activeNow: 2,
    seedMessages: [
      { id: "ac1", communityId: "anxiety-circle", anonymousName: "StormCloud", content: "Had a panic attack in a meeting today. Pretended to take notes.", timestamp: t(50) },
      { id: "ac2", communityId: "anxiety-circle", anonymousName: "ClearAir", content: "That is incredibly hard. Are you okay now?", timestamp: t(45) },
      { id: "ac3", communityId: "anxiety-circle", anonymousName: "StormCloud", content: "More embarrassed than hurt. I don't think anyone noticed.", timestamp: t(40) },
      { id: "ac4", communityId: "anxiety-circle", anonymousName: "ClearAir", content: "They didn't. You handled it. That takes strength.", timestamp: t(30) },
      { id: "ac5", communityId: "anxiety-circle", anonymousName: "GentleWave", content: "Box breathing — 4 in, 4 hold, 4 out. Saves me in meetings.", timestamp: t(10) },
    ],
  },
  {
    id: "loneliness",
    name: "Loneliness & Connection",
    category: "Relationships",
    description: "When you feel disconnected even in a crowd",
    emoji: "🕯️",
    sizeType: "small",
    memberCount: 6,
    activeNow: 1,
    seedMessages: [
      { id: "lo1", communityId: "loneliness", anonymousName: "TwilightMoss", content: "I have lots of acquaintances but no one I can call at 2am.", timestamp: t(180) },
      { id: "lo2", communityId: "loneliness", anonymousName: "IndigoTide", content: "That's a specific kind of loneliness. I know it exactly.", timestamp: t(160) },
      { id: "lo3", communityId: "loneliness", anonymousName: "TwilightMoss", content: "How do you even build that kind of friendship as an adult?", timestamp: t(140) },
      { id: "lo4", communityId: "loneliness", anonymousName: "IndigoTide", content: "Slowly. Consistently showing up. Being the one who reaches out first.", timestamp: t(100) },
      { id: "lo5", communityId: "loneliness", anonymousName: "CalmEmber", content: "Until then — we're here.", timestamp: t(30) },
    ],
  },
];

export const COMMUNITY_SUGGESTIONS: Record<Persona, string[]> = {
  pragati: ["burnout", "career-pressure", "anxiety-circle"],
  kulman: ["general-wellness", "breakup", "loneliness"],
};
